spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:fardin}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/shipping_service}
  data:
    rest:
      base-path: ${SPRING_DATA_REST_BASE_PATH:api}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
    consumer:
      key-deserializer: ${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER:org.springframework.kafka.support.serializer.JsonDeserializer}
      properties:
        spring.json.trusted-packages: ${SPRING_KAFKA_CONSUMER_TRUSTED_PACKAGES:*}

jwt:
  secret: ${JWT_SECRET:e1ad65c2e438d1805ae31d851c5756506d052b42ecdaebd3f88dba6f2caa18d239dd6cab8e0ede6736533e7104d1a5b85c340dffc7422037cb52aa7e5a741801064dacaa234f4626ea2158adf5768191dd6747b796d5b71bc4215cc61cc4e349812ff0b89046c752b9923dcbc1540a77ae6e69a188ebf879ee6fe767ee6648659b7e428568bfc6ed46e03a9db8a2c140a5d01adb45ddc30deae36b05ddf2f641e188d0571a81a4afe666bc1e551523fa5c069c29c9d787ede0664ac030541ae12a520066bc1573d99ea1d0d97bb1f5d1c5cfd6f6899d72f26e9204d1377404862198a369b5f2995c3982e6eca23c2aaf713c85feb9948fe90b86c7681f820c5c}
  expiration: ${JWT_EXPIRATION:86400000}
