spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: fardin
    password: 12345
    url: jdbc:mariadb://localhost:3306/shipping_service
  data:
    rest:
      base-path: api
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  config:
    import: optional:configserver://localhost:8888

server:
  port: 8060
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: e1ad65c2e438d1805ae31d851c5756506d052b42ecdaebd3f88dba6f2caa18d239dd6cab8e0ede6736533e7104d1a5b85c340dffc7422037cb52aa7e5a741801064dacaa234f4626ea2158adf5768191dd6747b796d5b71bc4215cc61cc4e349812ff0b89046c752b9923dcbc1540a77ae6e69a188ebf879ee6fe767ee6648659b7e428568bfc6ed46e03a9db8a2c140a5d01adb45ddc30deae36b05ddf2f641e188d0571a81a4afe666bc1e551523fa5c069c29c9d787ede0664ac030541ae12a520066bc1573d99ea1d0d97bb1f5d1c5cfd6f6899d72f26e9204d1377404862198a369b5f2995c3982e6eca23c2aaf713c85feb9948fe90b86c7681f820c5c
  expiration: 86400000