spring:
  config:
    import: optional:configserver:http://localhost:8888
  data:
    rest:
      base-path: /api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: fardin
    password: 12345
    url: jdbc:mariadb://localhost:3306/product_service


  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: file:/home/noorzai/uploads/images/

logging:
  level:
    org.springframework.web: DEBUG
