spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: ${SPRING_RABBITMQ_LISTENER_CONCURRENCY:1}
        max-concurrency: ${SPRING_RABBITMQ_LISTENER_MAX_CONCURRENCY:5}
        retry:
          enabled: ${SPRING_RABBITMQ_LISTENER_RETRY_ENABLED:true}
          max-attempts: ${SPRING_RABBITMQ_LISTENER_RETRY_MAX_ATTEMPTS:3}
          initial-interval: ${SPRING_RABBITMQ_LISTENER_RETRY_INITIAL_INTERVAL:1000}
    template:
      exchange: ${SPRING_RABBITMQ_TEMPLATE_EXCHANGE:product-validation.exchange}
      routing-key: ${SPRING_RABBITMQ_TEMPLATE_ROUTING_KEY:product-validation}
