spring:
  config:
    import: optional:configserver:http://localhost:8888
  data:
    rest:
      base-path: /api
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: fardin
    password: 12345
    url: jdbc:mariadb://localhost:3306/product_service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'



  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: file:/home/noorzai/uploads/images/


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG