spring:
  config:
    import: optional:configserver:http://localhost:8888


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 12345
    username: root
    url: jdbc:mariadb://localhost:3306/cart_service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update