spring:
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 12345
    username: root
    url: jdbc:mariadb://localhost:3306/cart_service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
